// lib/main.dart
//
// Kelimelik — App entry point.
// All credentials injected via --dart-define at build time.
//
// Run locally:
//   flutter run \
//     --dart-define=APP_ENV=dev \
//     --dart-define=SUPABASE_URL=https://xxx.supabase.co \
//     --dart-define=SUPABASE_ANON_KEY=eyJ... \
//     --dart-define=ADMOB_ANDROID_APP_ID=ca-app-pub-xxx \
//     --dart-define=ADMOB_IOS_APP_ID=ca-app-pub-xxx

import 'dart:io';
import 'package:intl/date_symbol_data_local.dart';
import 'package:app_tracking_transparency/app_tracking_transparency.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'core/config/app_config.dart';
import 'core/l10n/app_strings.dart';
import 'core/network/supabase_client.dart';
import 'core/router/app_router.dart';
import 'core/services/ad_service.dart';
import 'core/services/hive_service.dart';
import 'core/theme/app_theme.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await initializeDateFormatting();

  // ── Orientation ──────────────────────────────────────────────────────────────
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // ── System UI ────────────────────────────────────────────────────────────────
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light,
      systemNavigationBarColor: AppTheme.bgDeep,
      systemNavigationBarIconBrightness: Brightness.light,
    ),
  );

  // ── Hive (local storage + word database) ──────────────────────────────────────
  await HiveService.initialize();

  // ── Firebase ─────────────────────────────────────────────────────────────────
  try {
    // Note: firebase_options.dart is generated by `flutterfire configure`
    // For now we initialize without options (will add after Firebase project setup)
    await Firebase.initializeApp();

    FlutterError.onError = (details) {
      FirebaseCrashlytics.instance.recordFlutterFatalError(details);
    };
    PlatformDispatcher.instance.onError = (error, stack) {
      FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
      return true;
    };
    if (kDebugMode) {
      await FirebaseCrashlytics.instance.setCrashlyticsCollectionEnabled(false);
    }
  } catch (e) {
    debugPrint('[Firebase] Not configured — running without it: $e');
  }

  // ── Supabase ─────────────────────────────────────────────────────────────────
  await SupabaseClientService.initialize(
    url:     AppConfig.supabaseUrl,
    anonKey: AppConfig.supabaseAnonKey,
  );

  // ── ATT (iOS App Tracking Transparency) ──────────────────────────────────────
  if (Platform.isIOS) {
    final status = await AppTrackingTransparency.trackingAuthorizationStatus;
    if (status == TrackingStatus.notDetermined) {
      await Future.delayed(const Duration(milliseconds: 200));
      await AppTrackingTransparency.requestTrackingAuthorization();
    }
  }

  // ── AdMob ─────────────────────────────────────────────────────────────────────
  await AdService.initialize();

  // ── Run app ───────────────────────────────────────────────────────────────────
  runApp(const ProviderScope(child: KelimelikApp()));
}

// ─── Root widget ──────────────────────────────────────────────────────────────

class KelimelikApp extends ConsumerWidget {
  const KelimelikApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(appRouterProvider);
    final locale = ref.watch(localeProvider);

    return MaterialApp.router(
      title: AppConfig.appName,
      debugShowCheckedModeBanner: false,
      theme: AppTheme.darkTheme,
      routerConfig: router,
      locale: locale,
      supportedLocales: const [
        Locale('tr'),
        Locale('en'),
        Locale('es'),
        Locale('de'),
        Locale('fr'),
        Locale('pt'),
      ],
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
    );
  }
}
